server:
  port: 8081   # change per service

spring:
  datasource:
    url: jdbc:oracle:thin:@oracle-db:1521/XE
    username: ORDERS_USER
    password: orders123
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.OracleDialect

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8095/realms/microservices-realm
          jwk-set-uri: http://keycloak:8080/realms/microservices-realm/protocol/openid-connect/certs

logging:
  level:
    root: INFO
